eclipse-edc/GradlePlugins

- .github/release.yaml
- .github/workflows/release-runtime-metamodel.yml
- build.gradle.kts
- gradle.properties
- runtime-metamodel/build.gradle.kts
This PR adds two things:
1. a release workflow (identical to the main EDC repo)
2. a bit of logic for the build to be able to set the version on the CLI using the `-Pversion=...` parameter
To be able to easily create release and `SNAPSHOT` versions
no new code has been implemented, I merely copied the logic from the EDC repo
Closes #2
> feat(build): create release pipeline for `runtime-metamodel`

- autodoc/build.gradle.kts
- build.gradle.kts
- gradle.properties
Corrects some errors regarding the build file and the deployment urls:
- `groupId` and `version` is now applied to `allprojects` instead of only `subprojects`. this caused failures when initializing the staging repo.
- deployment urls were switched.
enable snapshot and release builds
> fix: use correct urls, apply group and version to all projects

- docs/developer/autodoc.md
Adds documentation for the `autodoc` plugin.
Documentation is good :)
> docs: add documentation for autodoc

- CODEOWNERS
- CONTRIBUTING.md
- LICENSE
- SECURITY.md
Adds basic documents to the repo, such as `LICENSE`, etc.
Compliance with EF
some documents simply refer to the EDC repo
Closes #6
> chore: add basic documents

- plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/dataspaceconnector/plugins/autodoc/AutodocPlugin.java
- plugins/autodoc/autodoc-processor/src/main/java/org/eclipse/dataspaceconnector/plugins/autodoc/core/processor/EdcModuleProcessor.java
Fixes a small type in the processor's output path override 
Puts the `edc.json` in the expected directory 
> fix: type in processor output path

- plugins/autodoc/autodoc-processor/src/test/java/org/eclipse/dataspaceconnector/plugins/autodoc/core/processor/EdcModuleProcessorTest.java
- plugins/module-names/module-names-plugin/README.md
- plugins/module-names/module-names-plugin/build.gradle.kts
- plugins/module-names/module-names-plugin/src/main/java/org/eclipse/dataspaceconnector/plugins/modulenames/CheckModuleNamesAction.java
- plugins/module-names/module-names-plugin/src/main/java/org/eclipse/dataspaceconnector/plugins/modulenames/ModuleNamesPlugin.java
- plugins/module-names/module-names-plugin/src/test/java/org/eclipse/dataspaceconnector/plugins/modulenames/ModuleNamesPluginTest.java
- settings.gradle.kts
The `ModuleNamesPlugin` from the EDC's `buildSrc` directory was moved to this repo and is accessible via the `org.eclipse.dataspaceconnector.module-names` plugin (same as before).
Moves all build sources out of the EDC repo to separate concerns.
- test was added to verify the action
- once this PR is merged, and the plugin is available from the snapshot repo, it should get removed from the EDC code base.
> feat: add check-module-names plugin

- plugins/autodoc/autodoc-processor/src/main/java/org/eclipse/dataspaceconnector/plugins/autodoc/core/processor/introspection/ExtensionIntrospector.java
- plugins/autodoc/autodoc-processor/src/main/java/org/eclipse/dataspaceconnector/plugins/autodoc/core/processor/introspection/ModuleIntrospector.java
- runtime-metamodel/src/main/java/org/eclipse/dataspaceconnector/runtime/metamodel/annotation/EdcSettingContext.java
- runtime-metamodel/src/main/java/org/eclipse/dataspaceconnector/runtime/metamodel/annotation/Setting.java
- runtime-metamodel/src/main/java/org/eclipse/dataspaceconnector/runtime/metamodel/annotation/SettingContext.java
Deprecates the `@EdcSetting` and `@EdcSettingContext` annotations, and introduces a new `@Setting` and `@SettingContext` annotations, both of which are exact copies of the old thing.
To keep consistent with the naming of all other metamodel annotations.
We need to do the deprecation and removing in two separate steps, otherwise there could be a time where builds in downstream projects fail, until the make the switch as well.
Closes #19
> refactor: deprecate EdcSetting, add Setting

- plugins/edc-build/src/main/java/org/eclipse/dataspaceconnector/plugins/edcbuild/EdcBuildBasePlugin.java
- plugins/edc-build/src/main/java/org/eclipse/dataspaceconnector/plugins/edcbuild/EdcBuildPlugin.java
- plugins/edc-build/src/main/java/org/eclipse/dataspaceconnector/plugins/edcbuild/conventions/JavaConvention.java
- plugins/edc-build/src/main/java/org/eclipse/dataspaceconnector/plugins/edcbuild/conventions/TestConvention.java
Aims at speeding the Gradle build by applying some simple principles:
- apply plugins only when necessary (root project vs every project)
- set recommended default config options
Speed up Gradle build
I followed mostly [this guide](https://docs.gradle.org/current/userguide/performance.html).
> perf: selectively apply plugins, add some perf options

- plugins/edc-build/src/main/java/org/eclipse/dataspaceconnector/plugins/edcbuild/conventions/JavaConvention.java
The build plugin now provides a default java tooling version.
increase convention, decrease configuration effort.
- a bug was also fixed when configuring the java compile task.
> feat: provide default java version

- NOTICE.md
- build.gradle.kts
- docs/legal/generateThirdPartyReport.sh
Adds a `NOTICE.md` and `LICENSE` file to the `META-INF` folder of all the jar archives that this project produces.
Compliance
- The `LICENSE` was copied verbatim from the EDC project
- The `NOTICE.md` file was in parts also copied, only the third-party section was regenerated using the included shell script
- the `generateThirdPartyReport.sh` was copied verbatim from EDC
Closes #29
> fix(doc): add NOTICE.md file to JAR

- gradle/libs.versions.toml
- plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/DefaultDependencyConvention.java
- plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/extensions/VersionsExtension.java
Reads the default versions, that the build plugin provides, from the version catalog, if one exists.
further centralize version management
- if no version catalog is found, a fallback value is used.
> feat(build): read default versions from version catalog

- plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/EdcBuildPlugin.java
- plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/DefaultDependencyConvention.java
- plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/NexusPublishingConvention.java
Fixes a build problem, where the `publishToSonatype` Gradle task was not found, because the nexus publishing convention was applied too late.
fix the build.
> fix: apply nexus convention during the config phase

- plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/SwaggerGeneratorConvention.java
- plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/extensions/SwaggerGeneratorExtension.java
- plugins/edc-build/src/test/java/org/eclipse/edc/plugins/edcbuild/conventions/SwaggerGeneratorConventionTest.java
adds the `apiGroup` to the `SwaggerGeneratorExtension` and appends it to the chosen `outputDir` for openapi generation.
To be able to group together several API modules.
Closes #40
> feat(build): add apiGroup to config

- plugins/edc-build/build.gradle.kts
- plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/EdcBuildBasePlugin.java
- plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/EdcBuildPlugin.java
- plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/ConventionFunctions.java
- plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/SwaggerGeneratorConvention.java
- plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/tasks/PrintApiGroupTask.java
- plugins/openapi-merger/README.md
- plugins/openapi-merger/build.gradle.kts
- plugins/openapi-merger/src/main/java/org/eclipse/edc/plugins/openapimerger/OpenApiMergerPlugin.java
- plugins/openapi-merger/src/main/java/org/eclipse/edc/plugins/openapimerger/tasks/MergeApiSpecByPathTask.java
- plugins/openapi-merger/src/test/java/org/eclipse/edc/plugins/modulenames/OpenApiMergerPluginTest.java
- settings.gradle.kts
Creates a new custom task, that extends the `OpenApiMergerTask`, but gives us the opportunity to supply `input` and `output` directories via command line arguments:
```bash
./gradlew :mergeApiSpec --input=path/to/partial_api_spec --output=./merged.yaml
```
Allows to dynamically adapt the input directory, where all the partial api specs are. The plain `OpenApiMergerTask` would need to be configured e.g. using a pre-compiled script.
This way we can easily configure a CI job and produce separate api specs.
- I also created another task `apiGroups`, which prints each module's `apiGroup`. It is intended for developer convenience
Closes #41
> feat: create custom merger task

- plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/edc/plugins/autodoc/AutodocDependencyInjector.java
- plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/DependencyAnalysisConvention.java
Previously the `autodoc` annotation processor dependency was not excluded from the `dependency-analysis` plugin, which it should be. 
This PR fixes that.
Avoid wrong dependency analysis warnings.
.
.
> fix: explicitly exclude annotation processors from dep-analysis

- runtime-metamodel/src/main/java/org/eclipse/edc/runtime/metamodel/annotation/Setting.java
- settings.gradle.kts
Add a `defaultValue()` method to `@Setting`
Improve documentation
- set `rootProject.name` equal to the repository name `GradlePlugins`, for coherency
Closes #52
> feat: add defaultValue to `@Setting`

- .github/ISSUE_TEMPLATE/adoption_request.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
- gradle/libs.versions.toml
Add version catalog entry for `bouncycastle-jdk18on`
Version bump
- updated the issue/PR templates as well
Closes #64
> build(deps): Add bouncycastle jdk18on version

- plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/extensions/BuildExtension.java
Adds a `publish` flag to the plugin. The flag doesn't have any effect yet.
Once #67 is merged, publications will be added automatically and the `publish` flag can be used to disable this for a module. To ease the process of merging the changes in all repositories, the `publish` flag is added beforehand.
> chore: add publish flag

- plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/EdcBuildPlugin.java
- plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/Conventions.java
- plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/MavenPublicationConvention.java
Adds a convention for creating Maven publications for all library modules.
So that the `publishing` does not have to be explicitely configured for every module.
Closes #58
> feat: add Maven publication convention

- gradle/libs.versions.toml
Adds AWS Secrets Manager SDK
Because this is needed by another PR in connector repo.
> feat: add aws secrets manager library

- gradle/wrapper/gradle-wrapper.properties
- plugins/autodoc/autodoc-plugin/build.gradle.kts
- plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/edc/plugins/autodoc/AutodocDependencyInjector.java
- plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/edc/plugins/autodoc/AutodocPlugin.java
- plugins/edc-build/build.gradle.kts
- plugins/module-names/build.gradle.kts
- plugins/openapi-merger/build.gradle.kts
- plugins/test-summary/build.gradle.kts
Upgrades to Gradle 8.0
Keep up-to-date with Gradle developments, avoid potentially insurmountable technical debt down the line.
- Configuration blocks for the plugins had to adapted.
- resolving the module's own version for the `annotationProcessor` dependency (`autodoc`) is not allowed anymore, thus in case no explicit `processorVersion` is set in client projects, the injector simply sets `"<GROUP>:<ARTIFACT>:+"`, which is **NOT RECOMMENDED**. Thus, a warning is also logged. 
- The alternative would be to use an empty version string `"<GROUP>:<ARTIFACT>"`, causing the build to fail, or just throw a `GradleException`
.
> chore: upgrade to Gradle 8.0

- plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/MavenPublicationConvention.java
- plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/extensions/MavenPomExtension.java
Allows downstream projects to explicitly set the GroupID on the pom for publishing.
fixes a bug with publications
the default is still `org.eclipse.edc`
.
> fix: let users set the group id

- plugins/edc-build/README.md
- plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/MavenPublishingConvention.java
- plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/NexusPublishingConvention.java
- plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/Repositories.java
- plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/extensions/BuildExtension.java
Adds a few CLI arguments which allow specifying the Maven repository via CLI parameters:
- `edc.publish.url`: the URL of the Maven repo
- `edc.publish.repoName`: the name of the repo. Relevant for the `publish...` command
- `edc.publish.username`: the repo username
- `edc.publish.password`: the repo password
For example we could publish to a Nexus Repository running on localhost via:
```bash
./gradlew  -Dedc.publish.repoName=foobar \                                                                                                                                                                                                        
-Dedc.publish.url="http://localhost:8081/repository/maven-snapshots/" \
-Dedc.publish.user=admin \
-Dedc.publish.password=admin \
publishAllPublicationsToFoobar …
```
> feat: allow adding a repository to publish via CLI parameters

- gradle/wrapper/gradle-wrapper.properties
- plugins/autodoc/autodoc-plugin/build.gradle.kts
- plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/edc/plugins/autodoc/AutodocDependencyInjector.java
- plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/edc/plugins/autodoc/AutodocPlugin.java
- plugins/edc-build/build.gradle.kts
- plugins/module-names/build.gradle.kts
- plugins/openapi-merger/build.gradle.kts
- plugins/test-summary/build.gradle.kts
This reverts commit 5a821e3c9cab752c40e9162190ec800c183b8277.
Reverts gradle upgrade and set it back to 7.6
Gradle 8 impediment for #85 because, making the edc-build calling itself is causing gradle to fail with a dependency error that [seems to be related to the nexus-publish plugin](https://github.com/gradle-nexus/publish-plugin/issues/208)
-
> fix: Revert "chore: upgrade to Gradle 8.0 (#89)"

- plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/edc/plugins/autodoc/AutodocDependencyInjector.java
- plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/edc/plugins/autodoc/AutodocPlugin.java
fix regression introduced with the last PR
project.group() and groupId are two different things
> fix: annotation processor injector

- build.gradle.kts
- gradle.properties
- plugins/autodoc/autodoc-plugin/build.gradle.kts
- plugins/edc-build/README.md
- plugins/edc-build/build.gradle.kts
- plugins/module-names/build.gradle.kts
- plugins/openapi-merger/build.gradle.kts
- plugins/test-summary/build.gradle.kts
As documented in
https://docs.gradle.org/current/dsl/org.gradle.api.Project.html#org.gradle.api.Project:group
> fix: use gradle 'group' property instead of 'groupId'

- gradle/libs.versions.toml
- plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/DefaultDependencyConvention.java
This PR automatically adds the `com.fasterxml.jackson.dataformat:jackson-dataformat-xml` library to a project, if that projects depends on any Azure lib.
There is an apparent but with `com.azure.core`, which attempts to instantiate an `XmlMapper`, but does not declare the appropriate dependency. Whether this is by design or by mistake is not known.
The matching criterion for the dependency check is `<DEPENDENCYGROUP>.contains("azure")` because some groups are `com.microsoft.azure`, or `com.azure` etc.
.
> fix: supply Jackson Dataformat XML libs alongside azure

- plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/DefaultDependencyConvention.java
- plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/MavenPublicationConvention.java
Use null safe code to get version from the catalog
Avoid NPE
- suppressed annoying "text-fixtures" warning on publication
Closes #126
> fix: avoid NPE on DefaultDependencyConvention

- gradle/libs.versions.toml
- plugins/autodoc/autodoc-processor/src/main/java/org/eclipse/edc/plugins/autodoc/core/processor/EdcModuleProcessor.java
Removes `gatling` version from catalog
It's not used anymore.
- add `EdcModuleProcessor.EDC_OUTPUTDIR_OVERRIDE` as supported option, this will avoid some warnings
Closes #139
> chore: remove unused gatling dependency

- build.gradle.kts
- gradle.properties
- plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/MavenArtifactConvention.java
- plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/extensions/MavenPomExtension.java
Set pom information defaults to avoid having to set them on every project.
simplify configuration
Closes #130
> feat: set pom information defaults

- plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/extensions/MavenPomExtension.java
Re-adds a previously deleted setter for the `groupId` 
Downstream projects could not override the group id
.
Closes .
> fix: re-add setter for grouId in the MavenPomExtension

- build.gradle.kts
- plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/JavaConvention.java
Change default java version to 17.
- cleanup build file a little
Closes #158
> build: switch default java version to 17

- plugins/autodoc/autodoc-processor/src/main/java/org/eclipse/edc/plugins/autodoc/core/processor/EdcModuleProcessor.java
update annotation processor source version to 17
fix a warning
part of #158
> build: update annotation processor source version to 17

- buildSrc/gradle.properties
- docs/legal/generateThirdPartyReport.sh
- gradle.properties
- plugins/autodoc/autodoc-plugin/build.gradle.kts
- plugins/edc-build/build.gradle.kts
- plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/DefaultDependencyConvention.java
- plugins/module-names/build.gradle.kts
- plugins/openapi-merger/build.gradle.kts
- plugins/test-summary/build.gradle.kts
Update snapshot version to `0.1.0-SNAPSHOT`
Our next release version will be `0.1.0`, thus the next snapshot will be `0.1.1-SNAPSHOT` and the automatic version bump mechanism currently only bumps the `patch` version.
- added `implementation` dependencies onto the `:runtime-metamodel` module, which seems to break the cycle
_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/Connector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and our [etiquette for pull requests](https://github.com/eclipse-edc/Connector/blob/main/pr_etiquette.md)._
> chore: update snapshot version to 0.1.0-SNAPSHOT

- plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/JarConvention.java
Adds the `DEPENDENCIES` file to every jar we generate.
Every artefact we distribute should contain license information and information about other software it uses.
Please note that this fix includes the `DEPENDENCIES` file _at root level_, which contains _all_ dependencies of a project. There seems to be no (easy) way to only include a subproject's dependencies, unless we actually create a Gradle Dash Plugin.
\cc @SebastianBezold
> feat: add DEPENDENCIES file to jars

- DEPENDENCIES
- buildSrc/build.gradle.kts
- gradle/libs.versions.toml
- plugins/autodoc/autodoc-converters/README.md
- plugins/autodoc/autodoc-converters/build.gradle.kts
- plugins/autodoc/autodoc-converters/src/main/java/org/eclipse/edc/plugins/autodoc/json/JsonManifestReader.java
- plugins/autodoc/autodoc-converters/src/main/java/org/eclipse/edc/plugins/autodoc/markdown/MarkdownManifestRenderer.java
- plugins/autodoc/autodoc-converters/src/main/java/org/eclipse/edc/plugins/autodoc/spi/ManifestConverterException.java
- plugins/autodoc/autodoc-converters/src/main/java/org/eclipse/edc/plugins/autodoc/spi/ManifestReader.java
- plugins/autodoc/autodoc-converters/src/main/java/org/eclipse/edc/plugins/autodoc/spi/ManifestRenderer.java
- plugins/autodoc/autodoc-converters/src/main/java/org/eclipse/edc/plugins/autodoc/spi/ManifestWriter.java
- plugins/autodoc/autodoc-converters/src/test/java/org/eclipse/edc/plugins/autodoc/json/JsonManifestReaderTest.java
- plugins/autodoc/autodoc-converters/src/test/java/org/eclipse/edc/plugins/autodoc/markdown/MarkdownManifestRendererTest.java
- plugins/autodoc/autodoc-converters/src/test/resources/example_manifest.json
- plugins/autodoc/autodoc-converters/src/test/resources/invalid_manifest.json
- plugins/autodoc/autodoc-converters/src/test/resources/simple_manifest.json
- plugins/autodoc/autodoc-plugin/build.gradle.kts
- plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/edc/plugins/autodoc/AutodocPlugin.java
- plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/edc/plugins/autodoc/tasks/JsonFileAppender.java
- plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/edc/plugins/autodoc/tasks/MarkdownRendererTask.java
- plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/edc/plugins/autodoc/tasks/MergeManifestsTask.java
- settings.gradle.kts
Adds a task `doc2md`, that takes the output JSON of `autodoc` and converts it into a Markdown file in the same directory (i.e. the `build/` directory).
If there is a `manifest.json` in the root `build/` dir, then that gets converted as well.
Easy and automatic generation of documentation.
- merging all the different `edc.json` files is async, so `./gradlew mergeManifest` and `./gradlew doc2md` _must_ be separate gradle invocations
- there is no dependency `doc2md` -> `mergeManifest` whatsoever
> feat: add manifest-to-markdown renderer

- plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/edc/plugins/autodoc/AutodocExtension.java
- plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/edc/plugins/autodoc/AutodocPlugin.java
- plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/edc/plugins/autodoc/tasks/ManifestDownloadTask.java
- plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/edc/plugins/autodoc/tasks/MarkdownRendererTask.java
- plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/edc/plugins/autodoc/tasks/MergeManifestsTask.java
- plugins/autodoc/autodoc-plugin/src/test/java/org/eclipse/edc/plugins/autodoc/AutodocPluginTest.java
This PR adds a gradle task `downloadManifests`, that downloads the `-manifest.json` from Maven for every `org.eclipse.edc` dependency.
Downstream projects, such as Tractus-X, that have dependencies onto EDC modules, can now merge _their_ autodoc manifests with those coming from EDC.
Usually, the sequence is this:
```shell
./gradlew autodoc
./gradlew downloadManifests
./gradlew mergeManifests
./gradlew doc2md
```
which will produce a Markdown file containing documentation about the code base plus any transitive EDC dependencies.
Alternatively, they can be run together:
```shell
./gradlew autodoc downloadManifests mergeManifests doc2md --no-parallel
```
easily create documentation
- these gradle tasks run async and potentially multithreaded, so they really should be called in separate …
> feat: download transitive autodoc manifests

- DEPENDENCIES
- plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/RepositoriesConvention.java
Removes the fraunhofer repository
It's not needed anymore and sometimes it returns errors that block the release process (e.g. https://github.com/eclipse-edc/Release/actions/runs/6844409607/job/18617673400)
> build: remove fraunhofer repository as it is not needed anymore

- DEPENDENCIES
- plugins/autodoc/autodoc-processor/src/main/java/org/eclipse/edc/plugins/autodoc/core/processor/introspection/ExtensionIntrospector.java
- plugins/autodoc/autodoc-processor/src/test/java/org/eclipse/edc/plugins/autodoc/core/processor/Constants.java
- plugins/autodoc/autodoc-processor/src/test/java/org/eclipse/edc/plugins/autodoc/core/processor/EdcModuleProcessorExtensionTest.java
- plugins/autodoc/autodoc-processor/src/test/java/org/eclipse/edc/plugins/autodoc/core/processor/testextensions/SettingContextExtension.java
Support the `context` property in Setting annotation which allows to provide a custom `prefix` for the `Setting`  in the autodoc.
If no context is provider the behavior is the same as before.
documentation
Closes #191
> feat(autodoc): suppoort context property on autodoc

- buildSrc/build.gradle.kts
Add missing task `output` and move the logic into the `doLast` block 
fix release
> build: add output to createVersions task

- plugins/edc-build/build.gradle.kts
Sets additional source path relative to the module.
> build: set source dir relative to the module path

- DEPENDENCIES
- build.gradle.kts
- buildSrc/build.gradle.kts
- gradle/libs.versions.toml
- plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/CheckstyleConvention.java
Currently is not possible to let the `edc-build` plugin use the latest checkstyle version by default.
This PR adds `checkstyle` dependency on the version catalog and put the version as the default version set by the `CheckstyleConvention`. This way, when not overrode, it will take the one in the catalog, that, thanks to dependabot, will supposedly updated to the latest one.
version updates
- looks like in the last version of checkstyle there are issues with guava (that's a dependency): https://github.com/google/guava/issues/6825 so I set the checkstyle version to the latest working one
_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-request) and …
> build: make default checkstyle version be updated by dependabot

- DEPENDENCIES
- buildSrc/build.gradle.kts
- config/checkstyle/checkstyle.xml
- config/checkstyle/java.header
- plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/edc/plugins/autodoc/AutodocPlugin.java
- plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/CheckstyleConvention.java
Currently the `checkstyle` plugin permits warnings, but that's not ok (in fact currently there are two warns logged into the console, which I fixed in this PR).
> feat: set checkstyle max warnings 0 by default

- plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/EdcBuildPlugin.java
- plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/Conventions.java
- plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/PrintClasspathConvention.java
- plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/tasks/PrintClasspathTask.java
registers the `printClasspath` task for every project that applies `edc-build` plugin
avoid duplication
Closes #230
> feat: make edc-build register printClasspath plugin

- plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/TestConvention.java
This PR adds a flag `excludeTags` to exclude certain test tags, analogous to the `includeTags` flag. That way
we can execute `./gradlew test -DrunAllTests -DexcludeTags="foo,bar"`, effectively blacklisting certain tags.
Sometimes its easier to blacklist certain tags, than whitelist all the others.
_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-request) and our [etiquette for pull …
> feat: add excludeTags flag

- DEPENDENCIES
- buildSrc/build.gradle.kts
- gradle/libs.versions.toml
- plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/SwaggerResolveConvention.java
- plugins/edc-build/src/test/java/org/eclipse/edc/plugins/edcbuild/conventions/SwaggerResolveConventionTest.java
Make dependabot take care of swagger plugin version
Closes #236 
> build: make swagger be upgraded by dependabot

- DEPENDENCIES
- gradle/wrapper/gradle-wrapper.properties
Bumps gradle wrapper to 8.8
dependency update
> build(deps): bump gradle wrapper to 8.8

- DEPENDENCIES
- gradle/libs.versions.toml
- plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/edc/plugins/autodoc/AutodocDependencyInjector.java
- plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/edc/plugins/autodoc/AutodocExtension.java
- plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/MavenArtifactConvention.java
- plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/SwaggerResolveConvention.java
Adds an `openapi` task, that generates the openapi spec file for a project that has the swagger plugin registered and publishes it as a maven artifact
documentation.
at this point a new "merge" task that merges the files from the subprojects build folders instead of the `resources` ones could be implemented (as it was done in `MergeManifestTask`)
Closes #244 
> feat: publish openapi spec as artifact

- DEPENDENCIES
- gradle/libs.versions.toml
Bumps nexus-publish plugin to 2.0.0
> build(deps): bump nexus-publish plugin to 2.0.0

- DEPENDENCIES
- plugins/autodoc/autodoc-converters/src/main/java/org/eclipse/edc/plugins/autodoc/html/HtmlManifestRenderer.java
- plugins/autodoc/autodoc-converters/src/main/java/org/eclipse/edc/plugins/autodoc/markdown/MarkdownManifestRenderer.java
- plugins/autodoc/autodoc-converters/src/main/resources/style.css
- plugins/autodoc/autodoc-converters/src/test/java/org/eclipse/edc/plugins/autodoc/html/HtmlManifestRendererTest.java
- plugins/autodoc/autodoc-converters/src/test/java/org/eclipse/edc/plugins/autodoc/markdown/MarkdownManifestRendererTest.java
- plugins/autodoc/autodoc-processor/src/main/java/org/eclipse/edc/plugins/autodoc/core/processor/introspection/ExtensionIntrospector.java
- plugins/autodoc/autodoc-processor/src/test/java/org/eclipse/edc/plugins/autodoc/core/processor/Constants.java
- plugins/autodoc/autodoc-processor/src/test/java/org/eclipse/edc/plugins/autodoc/core/processor/EdcModuleProcessorTest.java
- plugins/autodoc/autodoc-processor/src/test/java/org/eclipse/edc/plugins/autodoc/core/processor/testextensions/SampleExtensionWithoutAnnotation.java
Render `@Deprecated` setting as ~~strikethrough~~ in autodoc output
documentation
Closes #251 
> feat: render deprecated setting as strikethrough

- plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/OpenApiMergerConvention.java
- plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/extensions/SwaggerGeneratorExtension.java
Permits to set the openapi spec version with an `apiVersion` properties. 
currently it is not possible and it was necessary to set the whole project version, but spec and project version are (/should be) two completely different values.
- uniform the way with which it's possible to customize the api spec by reading also `apiTitle` and `apiDescription` that are currently evaluated in the single repo build files. 
- removed unused extension methods
Closes #256 
> feat: permit to set spec version with property

- .github/workflows/discord-webhook.yml
- DEPENDENCIES
- buildSrc/build.gradle.kts
- gradle/libs.versions.toml
- plugins/openapi-merger/build.gradle.kts
Compel `swagger-parser` version to 2.1.12 because the old version caused `example: null` entries in the openapi files (that cause mis-rendering in the UI)
- fixed typo in the discord webhook workflow
Closes #183
> fix: avoid 'example: null' entries in openapi by compel swagger-parser version

- plugins/autodoc/autodoc-converters/src/main/java/org/eclipse/edc/plugins/autodoc/markdown/MarkdownManifestRenderer.java
- plugins/autodoc/autodoc-converters/src/main/java/org/eclipse/edc/plugins/autodoc/spi/ManifestRenderer.java
- plugins/autodoc/autodoc-converters/src/test/java/org/eclipse/edc/plugins/autodoc/markdown/MarkdownManifestRendererTest.java
remove heading
use only the module name on the title, all the further information are logged after then
set "configuration" as heading 3
improve the visualization on the documentation website:
https://eclipse-edc.github.io/documentation/autodoc/connector/
> docs: improve markdown rendering

- plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/edc/plugins/autodoc/AutodocPlugin.java
- plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/edc/plugins/autodoc/tasks/AbstractManifestResolveTask.java
- plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/edc/plugins/autodoc/tasks/AutodocBomTask.java
- plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/edc/plugins/autodoc/tasks/Constants.java
- plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/edc/plugins/autodoc/tasks/DownloadManifestTask.java
- plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/edc/plugins/autodoc/tasks/MergeManifestsTask.java
- plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/edc/plugins/autodoc/tasks/ResolveManifestTask.java
Enables the autodoc functionality for BOM modules. To do that, simply invoke:
```shell
./gradlew -p <path/to/bom> autodocBom
```
or 
```shell
./gradlew :your:bom:module:autodocBom
```
then, after locally resolving all autodoc manifests of referenced modules, the `autodocBom` task puts the merged manifest in `build/edc.json` 
the normal `autodoc` task doesn't work on BOM modules because they typically don't contain code, thus the compiler isn't engaged, and `autodoc` doesn't run.
- if the `autodocBom` task is invoked on a project where the name _doesn't_ end with `"-bom"`, a warning is logged
- the `resolveManifest` and `downloadManifest` tasks don't generate empty files anymore (`null` instead of `InputStream.nullStream()`)
- added some description to the tasks
Closes # <-- _insert Issue …
> feat: add autodocBom task to generate Autodoc manifests for BOMs

- plugins/autodoc/autodoc-processor/src/main/java/org/eclipse/edc/plugins/autodoc/core/processor/EdcModuleProcessor.java
- plugins/autodoc/autodoc-processor/src/main/java/org/eclipse/edc/plugins/autodoc/core/processor/introspection/ExtensionIntrospector.java
- plugins/autodoc/autodoc-processor/src/main/java/org/eclipse/edc/plugins/autodoc/core/processor/introspection/ModuleIntrospector.java
this PR parses objects annotated with `@Configuration` and reads all the information from the `@Settings`-annotated elements within. In addition, the `ModuleIntrospector` now checks that `@Settings` may occur in extensions, or in objects annotated with `@Settings`, and `@Configuration`-annotated fields may only occur in extensions.
Preparatory work for the config injection feature
Contributes to https://github.com/eclipse-edc/Connector/issues/4610
_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submi …
> feat: autodoc parse @Configuration objects

- plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/edc/plugins/autodoc/tasks/AbstractManifestResolveTask.java
- plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/edc/plugins/autodoc/tasks/DependencySource.java
- plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/edc/plugins/autodoc/tasks/DependencySourceFactory.java
- plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/edc/plugins/autodoc/tasks/DownloadManifestTask.java
- plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/edc/plugins/autodoc/tasks/FileSource.java
- plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/edc/plugins/autodoc/tasks/HttpSource.java
- plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/edc/plugins/autodoc/tasks/ResolveManifestTask.java
improves the manifest resolution tasks and declares task outputs for the `downloadManifests` task.
In addition, this PR adds facilities to resolve dependency files from both HTTP and the file system. This could come in handy when dealing with local builds.
avoid unnecessary task invocations
> feat: optimize resolving manifests

- gradle/libs.versions.toml
- plugins/openapi-merger/build.gradle.kts
Fix the first build issue described in #298 by adding a missing dependency to the `openapi-merger` plugin module.
the other issue described in one issue comment it's still there, but it could be tackled separately.
Part of #298  
> build: add missing dependency to openapi-merger

- plugins/autodoc/autodoc-processor/src/main/java/org/eclipse/edc/plugins/autodoc/core/processor/introspection/ExtensionIntrospector.java
Makes the autodoc processor to read `description` attribute of `@Setting`, leaving `value` (deprecated) as fallback
autodoc
Closes #307 
> feat(autodoc): use description annotation field and value as fallback

- plugins/autodoc/autodoc-plugin/build.gradle.kts
- plugins/edc-build/build.gradle.kts
- plugins/module-names/build.gradle.kts
- plugins/test-summary/build.gradle.kts
Cleans up unneeded dependencies to runtime-metamodel
Demonstrate that we can get rid of the chicken-egg problem with the `edc-build` plugin, because the runtime metamodel is only needed for the `autodoc-plugin`, that could be extracted from this repo, while the edc-build plugin release could be detached from edc release and also published on gradle portal ([as suggested in this discussion](https://github.com/eclipse-edc/GradlePlugins/discussions/295))
_Please be sure to take a look at the [contributing …
> build: remove unneeded `runtime-metamodel` dependencies

- buildSrc/build.gradle.kts
- plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/NexusPublishingConvention.java
- plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/Repositories.java
- plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/RepositoriesConvention.java
- plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/RootBuildScriptConvention.java
Switches:
- snapshot repo url to `https://central.sonatype.com/repository/maven-snapshots/`
- nexus url to `https://ossrh-staging-api.central.sonatype.com/service/local/`
Keeps old snapshot repository to soften the transition
[_Briefly state why the change was necessary._](https://central.sonatype.org/publish/publish-portal-ossrh-staging-api/#plugins-tested-for-compatibility)
_Please @-mention the committer that will sponsor your feature_.
Closes #341
_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#s …
> build: switch repository url to the newest one

- plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/edc/plugins/autodoc/AutodocPlugin.java
Fixes the check to decide to add the manifest artifact to the publication.
To avoid issues like the ones that are arising during the nightlies: https://github.com/eclipse-edc/Connector/actions/runs/16562891660/job/46837009034
_Please @-mention the committer that will sponsor your feature_.
_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-request) and our [etiquette for pull requests](https://github.com/eclipse-edc/.github/blob/main/contrib …
> fix: autodoc publication manifest registration

- gradle/libs.versions.toml
- plugins/autodoc/autodoc-processor/build.gradle.kts
Fix the `boot-spi` dependency version to an actual release version
Avoid chicken-egg problem and it will make the repository always "buildable" also during nightly builds
- at this point that we made edc-build independent from EDC, to avoid this problem we should move some interfaces from `boot-spi` to `runtime-metamodel`, but given that's just a test dependency I guess we can live with that like it is
_Please @-mention the committer that will sponsor your feature_.
> build(deps): avoid chicken-egg problem on edc test dependency

- plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/MavenPublicationConvention.java
- plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/extensions/BuildExtension.java
- plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/tasks/WaitForPublishedArtifacts.java
Add a check on the `waitForPublishedArtifacts` to properly exclude modules that should not be published (despite having proper publications, like `edc-build`)
Avoid issues like this: https://github.com/eclipse-edc/GradlePlugins/actions/runs/17060584871/job/48366616897
_Please @-mention the committer that will sponsor your feature_.
_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-request) and our [etiquette for pull …
> fix: exclude modules that should not be published from the waitForPublishedArtifacts
